// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.15.8
// source: mp4_MJ.proto

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MapleJuice_Maple_FullMethodName     = "/cs425_mp3.MapleJuice/Maple"
	MapleJuice_MapleExec_FullMethodName = "/cs425_mp3.MapleJuice/MapleExec"
	MapleJuice_Juice_FullMethodName     = "/cs425_mp3.MapleJuice/Juice"
	MapleJuice_JuiceExec_FullMethodName = "/cs425_mp3.MapleJuice/JuiceExec"
)

// MapleJuiceClient is the client API for MapleJuice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MapleJuiceClient interface {
	Maple(ctx context.Context, in *MapleRequest, opts ...grpc.CallOption) (*MapleResponse, error)
	MapleExec(ctx context.Context, in *MapleExecRequest, opts ...grpc.CallOption) (*MapleExecResponse, error)
	Juice(ctx context.Context, in *JuiceRequest, opts ...grpc.CallOption) (*JuiceResponse, error)
	JuiceExec(ctx context.Context, in *JuiceExecRequest, opts ...grpc.CallOption) (*JuiceExecResponse, error)
}

type mapleJuiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMapleJuiceClient(cc grpc.ClientConnInterface) MapleJuiceClient {
	return &mapleJuiceClient{cc}
}

func (c *mapleJuiceClient) Maple(ctx context.Context, in *MapleRequest, opts ...grpc.CallOption) (*MapleResponse, error) {
	out := new(MapleResponse)
	err := c.cc.Invoke(ctx, MapleJuice_Maple_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mapleJuiceClient) MapleExec(ctx context.Context, in *MapleExecRequest, opts ...grpc.CallOption) (*MapleExecResponse, error) {
	out := new(MapleExecResponse)
	err := c.cc.Invoke(ctx, MapleJuice_MapleExec_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mapleJuiceClient) Juice(ctx context.Context, in *JuiceRequest, opts ...grpc.CallOption) (*JuiceResponse, error) {
	out := new(JuiceResponse)
	err := c.cc.Invoke(ctx, MapleJuice_Juice_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mapleJuiceClient) JuiceExec(ctx context.Context, in *JuiceExecRequest, opts ...grpc.CallOption) (*JuiceExecResponse, error) {
	out := new(JuiceExecResponse)
	err := c.cc.Invoke(ctx, MapleJuice_JuiceExec_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MapleJuiceServer is the server API for MapleJuice service.
// All implementations must embed UnimplementedMapleJuiceServer
// for forward compatibility
type MapleJuiceServer interface {
	Maple(context.Context, *MapleRequest) (*MapleResponse, error)
	MapleExec(context.Context, *MapleExecRequest) (*MapleExecResponse, error)
	Juice(context.Context, *JuiceRequest) (*JuiceResponse, error)
	JuiceExec(context.Context, *JuiceExecRequest) (*JuiceExecResponse, error)
	mustEmbedUnimplementedMapleJuiceServer()
}

// UnimplementedMapleJuiceServer must be embedded to have forward compatible implementations.
type UnimplementedMapleJuiceServer struct {
}

func (UnimplementedMapleJuiceServer) Maple(context.Context, *MapleRequest) (*MapleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Maple not implemented")
}
func (UnimplementedMapleJuiceServer) MapleExec(context.Context, *MapleExecRequest) (*MapleExecResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MapleExec not implemented")
}
func (UnimplementedMapleJuiceServer) Juice(context.Context, *JuiceRequest) (*JuiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Juice not implemented")
}
func (UnimplementedMapleJuiceServer) JuiceExec(context.Context, *JuiceExecRequest) (*JuiceExecResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JuiceExec not implemented")
}
func (UnimplementedMapleJuiceServer) mustEmbedUnimplementedMapleJuiceServer() {}

// UnsafeMapleJuiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MapleJuiceServer will
// result in compilation errors.
type UnsafeMapleJuiceServer interface {
	mustEmbedUnimplementedMapleJuiceServer()
}

func RegisterMapleJuiceServer(s grpc.ServiceRegistrar, srv MapleJuiceServer) {
	s.RegisterService(&MapleJuice_ServiceDesc, srv)
}

func _MapleJuice_Maple_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MapleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapleJuiceServer).Maple(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MapleJuice_Maple_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapleJuiceServer).Maple(ctx, req.(*MapleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MapleJuice_MapleExec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MapleExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapleJuiceServer).MapleExec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MapleJuice_MapleExec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapleJuiceServer).MapleExec(ctx, req.(*MapleExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MapleJuice_Juice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JuiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapleJuiceServer).Juice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MapleJuice_Juice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapleJuiceServer).Juice(ctx, req.(*JuiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MapleJuice_JuiceExec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JuiceExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapleJuiceServer).JuiceExec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MapleJuice_JuiceExec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapleJuiceServer).JuiceExec(ctx, req.(*JuiceExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MapleJuice_ServiceDesc is the grpc.ServiceDesc for MapleJuice service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MapleJuice_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cs425_mp3.MapleJuice",
	HandlerType: (*MapleJuiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Maple",
			Handler:    _MapleJuice_Maple_Handler,
		},
		{
			MethodName: "MapleExec",
			Handler:    _MapleJuice_MapleExec_Handler,
		},
		{
			MethodName: "Juice",
			Handler:    _MapleJuice_Juice_Handler,
		},
		{
			MethodName: "JuiceExec",
			Handler:    _MapleJuice_JuiceExec_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mp4_MJ.proto",
}
